"""empty message

Revision ID: 0c95a225aeb4
Revises: 1fd201f70378
Create Date: 2016-04-19 17:52:02.847826

"""

# revision identifiers, used by Alembic.
revision = '0c95a225aeb4'
down_revision = '1fd201f70378'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('century_millenium_number_fkey', 'century', type_='foreignkey')
    op.drop_column('century', 'millenium_number')
    op.drop_constraint('date_year_number_fkey', 'date', type_='foreignkey')
    op.drop_column('date', 'year_number')
    op.drop_constraint('year_century_number_fkey', 'year', type_='foreignkey')
    op.drop_column('year', 'century_number')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('year', sa.Column('century_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('year_century_number_fkey', 'year', 'century', ['century_number'], ['number'])
    op.add_column('date', sa.Column('year_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('date_year_number_fkey', 'date', 'year', ['year_number'], ['number'])
    op.add_column('century', sa.Column('millenium_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('century_millenium_number_fkey', 'century', 'millenium', ['millenium_number'], ['number'])
    ### end Alembic commands ###
