"""empty message

Revision ID: 171ee3b61139
Revises: None
Create Date: 2016-04-19 19:19:30.420082

"""

# revision identifiers, used by Alembic.
revision = '171ee3b61139'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('century',
    sa.Column('number', sa.Integer(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_table('coordinates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('long', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fact_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('label', sa.Unicode(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label'),
    sa.UniqueConstraint('name')
    )
    op.create_table('hist_place',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('label', sa.Unicode(length=255), nullable=True),
    sa.Column('description', sa.UnicodeText(), server_default='No description', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('hist_region',
    sa.Column('text', sa.UnicodeText(), server_default='No text', nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('label', sa.Unicode(length=255), nullable=True),
    sa.Column('description', sa.UnicodeText(), server_default='No description', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('millenium',
    sa.Column('number', sa.Integer(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_table('quadrant',
    sa.Column('hash', sa.String(length=9), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), server_default='', nullable=False),
    sa.Column('label', sa.Unicode(length=255), server_default='', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Unicode(length=50), server_default='', nullable=False),
    sa.Column('password', sa.String(length=255), server_default='', nullable=False),
    sa.Column('reset_password_token', sa.String(length=100), server_default='', nullable=False),
    sa.Column('email', sa.Unicode(length=255), server_default='', nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('first_name', sa.Unicode(length=50), server_default='', nullable=True),
    sa.Column('last_name', sa.Unicode(length=50), server_default='', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('year',
    sa.Column('number', sa.Integer(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_table('fact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('label', sa.Unicode(length=255), nullable=True),
    sa.Column('description', sa.UnicodeText(), server_default='No description', nullable=True),
    sa.Column('weight', sa.Integer(), server_default='5', nullable=False),
    sa.Column('start_date_millenium', sa.Integer(), nullable=True),
    sa.Column('start_date_century', sa.Integer(), nullable=True),
    sa.Column('start_date_year', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Integer(), nullable=True),
    sa.Column('end_date_millenium', sa.Integer(), nullable=True),
    sa.Column('end_date_century', sa.Integer(), nullable=True),
    sa.Column('end_date_year', sa.Integer(), nullable=True),
    sa.Column('end_date', sa.Integer(), nullable=True),
    sa.Column('text', sa.UnicodeText(), server_default='No text', nullable=True),
    sa.ForeignKeyConstraint(['end_date'], ['date.id'], ),
    sa.ForeignKeyConstraint(['end_date_century'], ['century.number'], ),
    sa.ForeignKeyConstraint(['end_date_millenium'], ['millenium.number'], ),
    sa.ForeignKeyConstraint(['end_date_year'], ['year.number'], ),
    sa.ForeignKeyConstraint(['start_date'], ['date.id'], ),
    sa.ForeignKeyConstraint(['start_date_century'], ['century.number'], ),
    sa.ForeignKeyConstraint(['start_date_millenium'], ['millenium.number'], ),
    sa.ForeignKeyConstraint(['start_date_year'], ['year.number'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('shape',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Integer(), nullable=True),
    sa.Column('end_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['end_date'], ['date.id'], ),
    sa.ForeignKeyConstraint(['start_date'], ['date.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hist_places_facts',
    sa.Column('fact_id', sa.Integer(), nullable=True),
    sa.Column('hist_place_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fact_id'], ['fact.id'], ),
    sa.ForeignKeyConstraint(['hist_place_id'], ['hist_place.id'], )
    )
    op.create_table('hist_regions_facts',
    sa.Column('fact_id', sa.Integer(), nullable=True),
    sa.Column('hist_region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fact_id'], ['fact.id'], ),
    sa.ForeignKeyConstraint(['hist_region_id'], ['hist_region.id'], )
    )
    op.create_table('shapes_coordinates',
    sa.Column('shape_id', sa.Integer(), nullable=True),
    sa.Column('coordinates_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coordinates_id'], ['coordinates.id'], ),
    sa.ForeignKeyConstraint(['shape_id'], ['shape.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shapes_coordinates')
    op.drop_table('hist_regions_facts')
    op.drop_table('hist_places_facts')
    op.drop_table('users_roles')
    op.drop_table('shape')
    op.drop_table('fact')
    op.drop_table('year')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('quadrant')
    op.drop_table('millenium')
    op.drop_table('hist_region')
    op.drop_table('hist_place')
    op.drop_table('fact_type')
    op.drop_table('date')
    op.drop_table('coordinates')
    op.drop_table('century')
    ### end Alembic commands ###
