"""empty message

Revision ID: 1cb05bc6b2b3
Revises: 261ae3db8a63
Create Date: 2016-05-03 17:30:55.512861

"""

# revision identifiers, used by Alembic.
revision = '1cb05bc6b2b3'
down_revision = '261ae3db8a63'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('georegions_subgeoregions',
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['geo_region.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['geo_region.id'], )
    )
    op.drop_constraint('geo_region_parent_region_id_fkey', 'geo_region', type_='foreignkey')
    op.drop_column('geo_region', 'parent_region_id')
    op.add_column('processes_subprocesses', sa.Column('child_id', sa.Integer(), nullable=True))
    op.add_column('processes_subprocesses', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.drop_constraint('processes_subprocesses_parent_process_id_fkey', 'processes_subprocesses', type_='foreignkey')
    op.drop_constraint('processes_subprocesses_child_process_id_fkey', 'processes_subprocesses', type_='foreignkey')
    op.create_foreign_key(None, 'processes_subprocesses', 'process', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'processes_subprocesses', 'process', ['child_id'], ['id'])
    op.drop_column('processes_subprocesses', 'parent_process_id')
    op.drop_column('processes_subprocesses', 'child_process_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processes_subprocesses', sa.Column('child_process_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('processes_subprocesses', sa.Column('parent_process_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'processes_subprocesses', type_='foreignkey')
    op.drop_constraint(None, 'processes_subprocesses', type_='foreignkey')
    op.create_foreign_key('processes_subprocesses_child_process_id_fkey', 'processes_subprocesses', 'process', ['child_process_id'], ['id'])
    op.create_foreign_key('processes_subprocesses_parent_process_id_fkey', 'processes_subprocesses', 'process', ['parent_process_id'], ['id'])
    op.drop_column('processes_subprocesses', 'parent_id')
    op.drop_column('processes_subprocesses', 'child_id')
    op.add_column('geo_region', sa.Column('parent_region_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('geo_region_parent_region_id_fkey', 'geo_region', 'geo_region', ['parent_region_id'], ['id'])
    op.drop_table('georegions_subgeoregions')
    ### end Alembic commands ###
