"""empty message

Revision ID: 1f927765ceaf
Revises: 2731e623ed4e
Create Date: 2016-05-01 03:03:06.881678

"""

# revision identifiers, used by Alembic.
revision = '1f927765ceaf'
down_revision = '2731e623ed4e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hist_place', sa.Column('trusted', sa.Boolean(), nullable=True))
    op.add_column('hist_region', sa.Column('trusted', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hist_region', 'trusted')
    op.drop_column('hist_place', 'trusted')
    ### end Alembic commands ###
