"""empty message

Revision ID: 1fd201f70378
Revises: 965e24f5a1ba
Create Date: 2016-04-19 17:34:01.686710

"""

# revision identifiers, used by Alembic.
revision = '1fd201f70378'
down_revision = '965e24f5a1ba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fact_shape_fkey', 'fact', type_='foreignkey')
    op.drop_constraint('fact_fact_type_fkey', 'fact', type_='foreignkey')
    op.drop_column('fact', 'shape')
    op.drop_column('fact', 'fact_type')
    op.drop_constraint('shape_fact_id_fkey', 'shape', type_='foreignkey')
    op.drop_column('shape', 'fact_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shape', sa.Column('fact_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('shape_fact_id_fkey', 'shape', 'fact', ['fact_id'], ['id'])
    op.add_column('fact', sa.Column('fact_type', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fact', sa.Column('shape', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fact_fact_type_fkey', 'fact', 'fact_type', ['fact_type'], ['id'])
    op.create_foreign_key('fact_shape_fkey', 'fact', 'shape', ['shape'], ['id'])
    ### end Alembic commands ###
