"""empty message

Revision ID: 261ae3db8a63
Revises: 4ed8100f4343
Create Date: 2016-05-03 16:43:34.183212

"""

# revision identifiers, used by Alembic.
revision = '261ae3db8a63'
down_revision = '4ed8100f4343'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('process_parent_process_id_fkey', 'process', type_='foreignkey')
    op.drop_column('process', 'parent_process_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process', sa.Column('parent_process_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('process_parent_process_id_fkey', 'process', 'process', ['parent_process_id'], ['id'])
    ### end Alembic commands ###
