"""empty message

Revision ID: 2731e623ed4e
Revises: None
Create Date: 2016-04-30 23:03:31.038312

"""

# revision identifiers, used by Alembic.
revision = '2731e623ed4e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('date_hist_region_id_fkey', 'date', type_='foreignkey')
    op.drop_constraint('date_hist_place_id_fkey', 'date', type_='foreignkey')
    op.drop_column('date', 'hist_region_id')
    op.drop_column('date', 'hist_place_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('date', sa.Column('hist_place_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('date', sa.Column('hist_region_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('date_hist_place_id_fkey', 'date', 'hist_place', ['hist_place_id'], ['id'])
    op.create_foreign_key('date_hist_region_id_fkey', 'date', 'hist_region', ['hist_region_id'], ['id'])
    ### end Alembic commands ###
