"""empty message

Revision ID: 2b7f5a319ce3
Revises: None
Create Date: 2016-04-24 02:15:20.015752

"""

# revision identifiers, used by Alembic.
revision = '2b7f5a319ce3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hist_place', sa.Column('end_date_id', sa.Integer(), nullable=True))
    op.add_column('hist_place', sa.Column('start_date_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hist_place', 'date', ['start_date_id'], ['id'])
    op.create_foreign_key(None, 'hist_place', 'date', ['end_date_id'], ['id'])
    op.add_column('shape', sa.Column('hist_place_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shape', 'hist_place', ['hist_place_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shape', type_='foreignkey')
    op.drop_column('shape', 'hist_place_id')
    op.drop_constraint(None, 'hist_place', type_='foreignkey')
    op.drop_constraint(None, 'hist_place', type_='foreignkey')
    op.drop_column('hist_place', 'start_date_id')
    op.drop_column('hist_place', 'end_date_id')
    ### end Alembic commands ###
