"""empty message

Revision ID: 6c3fe444ff76
Revises: dce3d7d42da8
Create Date: 2016-04-27 22:45:42.194505

"""

# revision identifiers, used by Alembic.
revision = '6c3fe444ff76'
down_revision = 'dce3d7d42da8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hist_regions_hist_places',
    sa.Column('hist_region_id', sa.Integer(), nullable=True),
    sa.Column('hist_place_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hist_place_id'], ['hist_place.id'], ),
    sa.ForeignKeyConstraint(['hist_region_id'], ['hist_region.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hist_regions_hist_places')
    ### end Alembic commands ###
