"""empty message

Revision ID: 71779c7ce006
Revises: ef0a021c73d2
Create Date: 2016-04-27 14:58:37.871703

"""

# revision identifiers, used by Alembic.
revision = '71779c7ce006'
down_revision = 'ef0a021c73d2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hist_region', sa.Column('next_region_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hist_region', 'hist_region', ['next_region_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hist_region', type_='foreignkey')
    op.drop_column('hist_region', 'next_region_id')
    ### end Alembic commands ###
