"""empty message

Revision ID: 736b347c1ee2
Revises: 17832b570d17
Create Date: 2016-04-18 19:52:41.342607

"""

# revision identifiers, used by Alembic.
revision = '736b347c1ee2'
down_revision = '17832b570d17'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quadrant',
    sa.Column('hash', sa.String(length=9), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('hash')
    )
    op.add_column('shape', sa.Column('end_date', sa.Integer(), nullable=True))
    op.add_column('shape', sa.Column('start_date', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shape', 'date', ['end_date'], ['id'])
    op.create_foreign_key(None, 'shape', 'date', ['start_date'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shape', type_='foreignkey')
    op.drop_constraint(None, 'shape', type_='foreignkey')
    op.drop_column('shape', 'start_date')
    op.drop_column('shape', 'end_date')
    op.drop_table('quadrant')
    ### end Alembic commands ###
