"""empty message

Revision ID: 75cc11349479
Revises: 736b347c1ee2
Create Date: 2016-04-18 23:26:08.500244

"""

# revision identifiers, used by Alembic.
revision = '75cc11349479'
down_revision = '736b347c1ee2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coordinates', sa.Column('quadrant_hash', sa.String(), nullable=True))
    op.create_foreign_key(None, 'coordinates', 'quadrant', ['quadrant_hash'], ['hash'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coordinates', type_='foreignkey')
    op.drop_column('coordinates', 'quadrant_hash')
    ### end Alembic commands ###
