"""empty message

Revision ID: 965e24f5a1ba
Revises: dd9c9aeaa855
Create Date: 2016-04-18 23:40:31.809406

"""

# revision identifiers, used by Alembic.
revision = '965e24f5a1ba'
down_revision = 'dd9c9aeaa855'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('coordinates_quadrant_hash_fkey', 'coordinates', type_='foreignkey')
    op.drop_column('coordinates', 'quadrant_hash')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coordinates', sa.Column('quadrant_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('coordinates_quadrant_hash_fkey', 'coordinates', 'quadrant', ['quadrant_hash'], ['hash'])
    ### end Alembic commands ###
