"""empty message

Revision ID: dce3d7d42da8
Revises: 71779c7ce006
Create Date: 2016-04-27 15:34:41.858513

"""

# revision identifiers, used by Alembic.
revision = 'dce3d7d42da8'
down_revision = '71779c7ce006'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hist_region', sa.Column('prev_region_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hist_region', 'hist_region', ['prev_region_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hist_region', type_='foreignkey')
    op.drop_column('hist_region', 'prev_region_id')
    ### end Alembic commands ###
