"""empty message

Revision ID: ef0a021c73d2
Revises: 2b7f5a319ce3
Create Date: 2016-04-26 16:04:56.613644

"""

# revision identifiers, used by Alembic.
revision = 'ef0a021c73d2'
down_revision = '2b7f5a319ce3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hist_region', sa.Column('end_date_id', sa.Integer(), nullable=True))
    op.add_column('hist_region', sa.Column('start_date_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hist_region', 'date', ['end_date_id'], ['id'])
    op.create_foreign_key(None, 'hist_region', 'date', ['start_date_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hist_region', type_='foreignkey')
    op.drop_constraint(None, 'hist_region', type_='foreignkey')
    op.drop_column('hist_region', 'start_date_id')
    op.drop_column('hist_region', 'end_date_id')
    ### end Alembic commands ###
